version: '3.8'
services:
  app:
    build: ./SL.Api
    environment:
      LOGGER_PROVIDER: os
    ports:
      - "5000:8080"#Swagger UI
    depends_on:
      - os
  os:
    image: opensearchproject/opensearch
    environment:
      xpack.security.enabled: 'false'
      discovery.type: 'single-node'
      #for multi node es  https://www.elastic.co/guide/en/elasticsearch/reference/7.5/docker.html#docker-compose-file
    ports:
      - "5001:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    environment:
      ELASTICSEARCH_HOSTS: http://os:9200
    ports:
      - "5002:5601"
    depends_on:
      - os
volumes:
  es_data:
