version: '3.8'
services:
  app:
    build: ./SL.Api
    environment:
      LOGGER_PROVIDER: seq
    ports:
      - "5000:8080"#DOC Swagger UI
    depends_on: 
      - seq
  seq:
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: Y
    ports:
      - "5001:80"#Seq UI
      #Seq ingestion port at 5341
    volumes:
      - seq_data:/data

volumes:
  seq_data:
